version: '3.1'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"

  bookery:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  worker:
    restart: always
    build: .
    depends_on:
      - redis
      - bookery
    command: 'celery -A bookery worker -l info'

  beat:
      restart: always
      build: .
      depends_on:
        - redis
        - bookery
        - worker
      command: 'celery -A bookery beat -l info'

